### PR TITLE
Fix to maintain transparency in PDF

### PR DESCRIPTION
**Pull request by JacobD10**
Implemented a fix to maintain transparency (alpha) in PDF files (issue #108)

### CODE REVIEW

**Comment by altmany** [comment]
Thanks Jacob. 

Some feedback:
1. why did you not integrate this fix within `print2eps` but externally, in export_fig? it would make more sense, and would also avoid the need to read/write the EPS file (performance) since fstrm is already processed in `print2eps`
2. why not *always* perform the conversion? `-transparent` is reserved/documented for the background transparency, not for patches... What's the risk/downside?
3. you should really check `if using_hg2`, because your code will only work in HG2, not HG1
4. what happens to all elements beneath the one where you set the `.setopacityalpha` value? does it also use this same alpha value? if so, shouldn't you unset the alpha when the element is done?

**Comment by JacobD10** [comment]
1) Woops, probably should move the fix to `print2eps` I started doing it in there but hit issues so moved outside, then fixed the issues but kept working in export_fig. :| Let me know if you want me to move it!
2) I felt that if the fix ran all the time (i.e. without a flag such as '-transparent') then it would increase the likely hood of hitting the "rare" case where the color change for ID purposes would conflict with an existing patch color. So if a flag is used like '-transparent' at least that reduces the likely hood. Perhaps a new or different flag could be added? or it could be removed altogether if you prefer.
3) Forgot about that check, can add that.
4) From what I gathered from testing the `.setopacityalpha` value only sets the current elements opacity and further elements aren't changed.

**Comment by JacobD10** [comment]
Ok, addressed all of your feedback and pushed a new commit.

**Comment by ndattani** [comment]
Thank you for the fix JacobD10 ! 
I've been waiting for this for some time (but lacked the knowledge to make the fix that you did).
1. Which file(s) in my "export_fig-master" folder should I change? 
2. Once I download said file(s), if I have something in the Figure Window which I'd like to export as a vector graphic which maintains the alpha in the figure window, what command should I run?
3. Does this fix use any features which were only introduced after 2014b ?

Cheers!

**Comment by altmany** [comment]
@ndattani - Jacob's fix was already merged into `export_fig` on September 2015. Simply download that version (or the latest one) to get it.

**Comment by JacobD10** [comment]
@ndattani Glad I could help.
1. The only file changed is _print2eps.m_.
2. There are no extra commands to run as shown in the example code above.
3. I believe it does use features only introduced in HG2. It may be possible to tweak this for earlier versions, though, I'm not sure.

**Pull request merged**
